name: Deploy to Production

# Deploy to production when code is merged to main branch
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual deployment

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    
    # Add PostgreSQL database service with PostGIS
    services:
      postgres:
        image: postgis/postgis:17-3.4
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: courtpulse_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci
      
      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Run tests
        run: npm run test:ci
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: courtpulse_test
          DB_USER: postgres
          DB_PASSWORD: postgres

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run type-check

      - name: Build project
        run: npm run build

      - name: Deploy Backend to Render (Production)
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service: courtpulse-backend  # Your existing production backend service
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true

      - name: Deploy Frontend to Vercel (Production)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
